/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

/**
 *
 * @author Migara Kavishan
 */
public class EmpManageView extends javax.swing.JFrame {

    /**
     * Creates new form EmpManageView
     */
    public EmpManageView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnMngInovice = new javax.swing.JButton();
        btnMngRepairJobs = new javax.swing.JButton();
        btnMngPartSupplier = new javax.swing.JButton();
        btnMngSpareParts = new javax.swing.JButton();
        btnRegCustomer = new javax.swing.JButton();
        btnAllocateEmp = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 102, 102,80));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Time Ticker");

        btnMngInovice.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnMngInovice.setText("Manage Invoices");
        btnMngInovice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMngInoviceActionPerformed(evt);
            }
        });

        btnMngRepairJobs.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnMngRepairJobs.setText("Manage Repairing Jobs");
        btnMngRepairJobs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMngRepairJobsActionPerformed(evt);
            }
        });

        btnMngPartSupplier.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnMngPartSupplier.setText("Manage Parts Suppliers");
        btnMngPartSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMngPartSupplierActionPerformed(evt);
            }
        });

        btnMngSpareParts.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnMngSpareParts.setText("Manage Spare Parts");
        btnMngSpareParts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMngSparePartsActionPerformed(evt);
            }
        });

        btnRegCustomer.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnRegCustomer.setText("Register Customer");
        btnRegCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegCustomerActionPerformed(evt);
            }
        });

        btnAllocateEmp.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAllocateEmp.setText("Allocate Employees");
        btnAllocateEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAllocateEmpActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(204, 204, 204));
        btnBack.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1.setText("Manage Watch");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(btnMngInovice)
                        .addGap(18, 18, 18)
                        .addComponent(btnMngRepairJobs)
                        .addGap(12, 12, 12))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnMngSpareParts)
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRegCustomer))
                        .addGap(20, 20, 20)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnMngPartSupplier)
                    .addComponent(btnAllocateEmp))
                .addContainerGap(33, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(210, 210, 210))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addGap(265, 265, 265))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnMngRepairJobs)
                            .addComponent(btnMngPartSupplier)
                            .addComponent(btnMngInovice))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnMngSpareParts)
                            .addComponent(btnRegCustomer)
                            .addComponent(btnAllocateEmp))
                        .addGap(35, 35, 35)))
                .addComponent(jButton1)
                .addGap(34, 34, 34)
                .addComponent(btnBack)
                .addGap(58, 58, 58))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 610, 390));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org.me.mypics.resources/mng 1.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-190, -80, 1000, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        LoginUI Ui = new LoginUI();
        Ui.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnMngInoviceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMngInoviceActionPerformed
        // TODO add your handling code here:
        ManageInvoicesView Ui = new ManageInvoicesView();
        this.setVisible(false);
        Ui.setVisible(true);
    }//GEN-LAST:event_btnMngInoviceActionPerformed

    private void btnMngRepairJobsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMngRepairJobsActionPerformed
        // TODO add your handling code here:
        ManageRepairJobsView Ui = new ManageRepairJobsView();
        this.setVisible(false);
        Ui.setVisible(true);
    }//GEN-LAST:event_btnMngRepairJobsActionPerformed

    private void btnMngSparePartsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMngSparePartsActionPerformed
        // TODO add your handling code here:
        ManageSparePartsViews Ui = new ManageSparePartsViews();
        this.setVisible(false);
        Ui.setVisible(true);
    }//GEN-LAST:event_btnMngSparePartsActionPerformed

    private void btnMngPartSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMngPartSupplierActionPerformed
        // TODO add your handling code here:
        ManageSupplierView Ui = new ManageSupplierView();
        this.setVisible(false);
        Ui.setVisible(true);
    }//GEN-LAST:event_btnMngPartSupplierActionPerformed

    private void btnRegCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegCustomerActionPerformed
        // TODO add your handling code here:
        RegisterCustomerView Ui = new RegisterCustomerView();
        this.setVisible(false);
        Ui.setVisible(true);
    }//GEN-LAST:event_btnRegCustomerActionPerformed

    private void btnAllocateEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAllocateEmpActionPerformed
        // TODO add your handling code here:
        AllocateEmployeesView Ui = new AllocateEmployeesView();
        this.setVisible(false);
        Ui.setVisible(true);
    }//GEN-LAST:event_btnAllocateEmpActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        WatchUI Ui = new WatchUI();
        this.setVisible(false);
        Ui.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmpManageView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmpManageView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmpManageView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmpManageView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmpManageView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAllocateEmp;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnMngInovice;
    private javax.swing.JButton btnMngPartSupplier;
    private javax.swing.JButton btnMngRepairJobs;
    private javax.swing.JButton btnMngSpareParts;
    private javax.swing.JButton btnRegCustomer;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
