/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

/**
 *
 * @author Migara Kavishan
 */
public class MainManageView extends javax.swing.JFrame {

    /**
     * Creates new form MainManageView
     */
    public MainManageView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnMonthlyReport = new javax.swing.JButton();
        btnAllocateEmp = new javax.swing.JButton();
        btnMngInvoice = new javax.swing.JButton();
        btnMngRepairJobs = new javax.swing.JButton();
        btnRegCustomer = new javax.swing.JButton();
        btnMngPartSupplier = new javax.swing.JButton();
        btnMngSpareParts = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 102, 102,80));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Time Ticker");

        btnMonthlyReport.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnMonthlyReport.setText("Show Monthly Report");
        btnMonthlyReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMonthlyReportActionPerformed(evt);
            }
        });

        btnAllocateEmp.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnAllocateEmp.setText("Allocate Employee");
        btnAllocateEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAllocateEmpActionPerformed(evt);
            }
        });

        btnMngInvoice.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnMngInvoice.setText("Manage Invoices");
        btnMngInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMngInvoiceActionPerformed(evt);
            }
        });

        btnMngRepairJobs.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnMngRepairJobs.setText("Manage Repairing Jobs");
        btnMngRepairJobs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMngRepairJobsActionPerformed(evt);
            }
        });

        btnRegCustomer.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnRegCustomer.setText("Register Customer");
        btnRegCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegCustomerActionPerformed(evt);
            }
        });

        btnMngPartSupplier.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnMngPartSupplier.setText("Manage Parts Suppliers");
        btnMngPartSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMngPartSupplierActionPerformed(evt);
            }
        });

        btnMngSpareParts.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnMngSpareParts.setText("Manage Spare Parts");
        btnMngSpareParts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMngSparePartsActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(153, 153, 153));
        btnBack.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMngInvoice)
                    .addComponent(btnMonthlyReport)
                    .addComponent(btnRegCustomer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 133, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAllocateEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMngPartSupplier)
                    .addComponent(btnMngRepairJobs))
                .addGap(50, 50, 50))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(244, 244, 244)
                .addComponent(btnMngSpareParts)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addGap(41, 41, 41))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(259, 259, 259))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel2)
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMonthlyReport)
                    .addComponent(btnAllocateEmp))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMngRepairJobs, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnMngInvoice))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegCustomer)
                    .addComponent(btnMngPartSupplier))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(btnMngSpareParts)
                .addGap(18, 18, 18)
                .addComponent(btnBack)
                .addGap(29, 29, 29))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 690, 390));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org.me.mypics.resources/ghj.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-80, 0, 850, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAllocateEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAllocateEmpActionPerformed
        // TODO add your handling code here:
        AllocateEmployeesView Ui = new AllocateEmployeesView();
        this.setVisible(false);
        Ui.setVisible(true);
    }//GEN-LAST:event_btnAllocateEmpActionPerformed

    private void btnMngPartSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMngPartSupplierActionPerformed
        // TODO add your handling code here:
        ManageSupplierView Ui = new ManageSupplierView();
        this.setVisible(false);
        Ui.setVisible(true);
    }//GEN-LAST:event_btnMngPartSupplierActionPerformed

    private void btnMngSparePartsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMngSparePartsActionPerformed
        // TODO add your handling code here:
        ManageSparePartsViews Ui = new ManageSparePartsViews();
        this.setVisible(false);
        Ui.setVisible(true);
    }//GEN-LAST:event_btnMngSparePartsActionPerformed

    private void btnMngRepairJobsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMngRepairJobsActionPerformed
        // TODO add your handling code here:
        ManageRepairJobsView Ui = new ManageRepairJobsView();
        this.setVisible(false);
        Ui.setVisible(true);
    }//GEN-LAST:event_btnMngRepairJobsActionPerformed

    private void btnMngInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMngInvoiceActionPerformed
        // TODO add your handling code here:
        ManageInvoicesView Ui = new ManageInvoicesView();
        this.setVisible(false);
        Ui.setVisible(true);
    }//GEN-LAST:event_btnMngInvoiceActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        LoginUI Ui = new LoginUI();
        Ui.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnRegCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegCustomerActionPerformed
        // TODO add your handling code here:
        RegisterCustomerView Ui = new RegisterCustomerView();
        this.setVisible(false);
        Ui.setVisible(true);
    }//GEN-LAST:event_btnRegCustomerActionPerformed

    private void btnMonthlyReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMonthlyReportActionPerformed
        MonthlySalesReport Ui = new MonthlySalesReport();
        this.setVisible(false);
        Ui.setVisible(true);
    }//GEN-LAST:event_btnMonthlyReportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainManageView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainManageView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainManageView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainManageView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainManageView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAllocateEmp;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnMngInvoice;
    private javax.swing.JButton btnMngPartSupplier;
    private javax.swing.JButton btnMngRepairJobs;
    private javax.swing.JButton btnMngSpareParts;
    private javax.swing.JButton btnMonthlyReport;
    private javax.swing.JButton btnRegCustomer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
