/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import javax.swing.JOptionPane;
import Controllers.InvoiceController;
import Models.Invoice;
import java.util.ArrayList;

public class ManageInvoicesView extends javax.swing.JFrame {

    Invoice objInvoice;
    InvoiceController InvoiceControllerobj;
    Invoice[] InvoiceArray;
    ArrayList<Invoice> InvoiceList;
    int index;
    
    public static String valueCHK;
    
    public ManageInvoicesView() {
        initComponents();
        InvoiceControllerobj = new InvoiceController();
        InvoiceArray = new Invoice[100];
        InvoiceList = new ArrayList<>();
        index = 0;
        
        SaleComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblQty = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        txtInvoiceID = new javax.swing.JTextField();
        txtCustomerID = new javax.swing.JTextField();
        txtPrice = new javax.swing.JTextField();
        txtQuantity = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jcbSalesType = new javax.swing.JComboBox<>();
        txtWiD = new javax.swing.JTextField();
        LabelwID = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtDate = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0,80));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Manage Watch Sales Invoices");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Customer ID");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Invoice ID");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Price");

        lblQty.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblQty.setForeground(new java.awt.Color(255, 255, 255));
        lblQty.setText("Quantity");

        btnUpdate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnAdd.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnRemove.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnRemove.setText("Remove");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(153, 153, 153));
        btnBack.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Sales Type");

        jcbSalesType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Watch Sale", "Watch Repair" }));
        jcbSalesType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbSalesTypeActionPerformed(evt);
            }
        });

        LabelwID.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LabelwID.setForeground(new java.awt.Color(255, 255, 255));
        LabelwID.setText("ID");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Issue Date");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(LabelwID, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblQty, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCustomerID, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txtInvoiceID, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jcbSalesType, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(txtWiD, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtDate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtQuantity, javax.swing.GroupLayout.Alignment.LEADING)))
                                .addGap(146, 146, 146)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnBack)
                                    .addComponent(btnAdd)
                                    .addComponent(btnRemove)
                                    .addComponent(btnUpdate))))
                        .addGap(16, 16, 16))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(175, 175, 175))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel2)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtInvoiceID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdd)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnUpdate)
                        .addGap(18, 18, 18)
                        .addComponent(btnRemove))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jcbSalesType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelwID)
                            .addComponent(txtWiD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCustomerID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQty)
                    .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(txtDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(88, 88, 88))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBack)
                        .addGap(74, 74, 74))))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 690, 470));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org.me.mypics.resources/invo.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SaleComboBox(){
        String Value = jcbSalesType.getSelectedItem().toString();
        if (Value.equals("Watch Sale")){
            LabelwID.setText("Watch ID");
            lblQty.setVisible(true);
            txtQuantity.setVisible(true);
        }else if (Value.equals("Watch Repair")){
            LabelwID.setText("Watch Repair ID");
            lblQty.setVisible(false);
            txtQuantity.setVisible(false);
        }
    }
    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        String check = LoginUI.user;
        
        if (check.equals("emp")){
            EmpManageView Ui = new EmpManageView();
            this.setVisible(false);
            Ui.setVisible(true);
        } else if (check.equals("admn")){
            MainManageView Ui = new MainManageView();
            this.setVisible(false);
            Ui.setVisible(true);
        }
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        String Value = jcbSalesType.getSelectedItem().toString();
        valueCHK = Value;
        
        try{                    
            String CustomerID = txtCustomerID.getText();
            String WiD = txtWiD.getText();
            String InvoiceID = txtInvoiceID.getText();
            double Price = Double.parseDouble(txtPrice.getText());
            int Quantity = Integer.parseInt(txtQuantity.getText());
            String IssueDate = txtDate.getText();

            objInvoice = InvoiceControllerobj.addInvoice(InvoiceID, CustomerID, WiD, Price, Quantity, IssueDate);
            boolean result=InvoiceControllerobj.insertInvoiceToDB(objInvoice);
            InvoiceArray[index] = objInvoice;
            InvoiceList.add(InvoiceArray[index]);
            index++;           
            
            if(result){
                JOptionPane.showMessageDialog(rootPane, "Are you sure you want to Add record? ","Alert",1);
                JOptionPane.showMessageDialog(rootPane, (index) + " Customer have been Added to Database Successfully", "Info", 1);
            }else{
               JOptionPane.showMessageDialog(rootPane, "Error adding to Database", "Error", 0); 
            }
            
            
        }catch(RuntimeException ex){
            
            if (txtCustomerID.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane,"CustomerID is Empty","Error",0);
            }
            if(Value.equals("Watch Sale")){
                if(txtWiD.getText().isEmpty()) {
                JOptionPane.showMessageDialog(rootPane,"Watch ID is Empty","Error",0);
                }
            }else if (Value.equals("Watch Repair")){
                if(txtWiD.getText().isEmpty()) {
                JOptionPane.showMessageDialog(rootPane,"Watch Repair ID is Empty","Error",0);
                }
            }
            if(txtInvoiceID.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane,"InvoiceID is Empty","Error",0);
            }
            if (txtPrice.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane,"Price is Empty","Error",0);
            }
            if (txtQuantity.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane,"Quantity is Empty","Error",0);
            }  
            if (txtDate.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane,"Date is Empty","Error",0);
            }
        }
        
        
    }//GEN-LAST:event_btnAddActionPerformed

    private void jcbSalesTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbSalesTypeActionPerformed
        // TODO add your handling code here:
        String Value = jcbSalesType.getSelectedItem().toString();
        if (Value.equals("Watch Sale")){
            LabelwID.setText("Watch ID");
            lblQty.setVisible(true);
            txtQuantity.setVisible(true);
        }else if (Value.equals("Watch Repair")){
            LabelwID.setText("Watch Repair ID");
            lblQty.setVisible(false);
            txtQuantity.setVisible(false);
        }
    }//GEN-LAST:event_jcbSalesTypeActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        String Value = jcbSalesType.getSelectedItem().toString();
        valueCHK = Value;
        
        try{                    
            String CustomerID = txtCustomerID.getText();
            String WiD = txtWiD.getText();
            String InvoiceID = txtInvoiceID.getText();
            double Price = Double.parseDouble(txtPrice.getText());
            int Quantity = Integer.parseInt(txtQuantity.getText());
            String IssueDate = txtDate.getText();

            objInvoice = InvoiceControllerobj.updateInvoice(InvoiceID, CustomerID, WiD, Price, Quantity, IssueDate);
            boolean result=InvoiceControllerobj.updateInvoiceToDB(objInvoice);
            InvoiceArray[index] = objInvoice;
            InvoiceList.add(InvoiceArray[index]);
            index++;           
            
            if(result){
                JOptionPane.showMessageDialog(rootPane, "Are you sure you want to update record? ","Alert",1);
                JOptionPane.showMessageDialog(rootPane, (index) + " Record have been updated to Database Successfully", "Info", 1);
            }else{
               JOptionPane.showMessageDialog(rootPane, "Error updating to Database", "Error", 0); 
            }
            
            
        }catch(RuntimeException ex){
            
            if (txtCustomerID.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane,"CustomerID is Empty","Error",0);
            }
            if(Value.equals("Watch Sale")){
                if(txtWiD.getText().isEmpty()) {
                JOptionPane.showMessageDialog(rootPane,"Watch ID is Empty","Error",0);
                }
            }else if (Value.equals("Watch Repair")){
                if(txtWiD.getText().isEmpty()) {
                JOptionPane.showMessageDialog(rootPane,"Watch Repair ID is Empty","Error",0);
                }
            }
            if(txtInvoiceID.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane,"InvoiceID is Empty","Error",0);
            }
            if (txtPrice.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane,"Price is Empty","Error",0);
            }
            if (txtQuantity.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane,"Quantity is Empty","Error",0);
            }       
            if (txtDate.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane,"Date is Empty","Error",0);
            }
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        // TODO add your handling code here:
        String Value = jcbSalesType.getSelectedItem().toString();
        valueCHK = Value;
        
        try{                    
            String CustomerID = txtCustomerID.getText();
            String WiD = txtWiD.getText();
            String InvoiceID = txtInvoiceID.getText();
            double Price = Double.parseDouble(txtPrice.getText());
            int Quantity = Integer.parseInt(txtQuantity.getText());
            String IssueDate = txtDate.getText();

            objInvoice = InvoiceControllerobj.deleteInvoice(InvoiceID, CustomerID, WiD, Price, Quantity, IssueDate);
            boolean result=InvoiceControllerobj.deleteInvoiceToDB(objInvoice);
            InvoiceArray[index] = objInvoice;
            InvoiceList.add(InvoiceArray[index]);
            index++;           
            
            if(result){
                JOptionPane.showMessageDialog(rootPane, "Are you sure you want to remove record? ","Alert",1);
                JOptionPane.showMessageDialog(rootPane, (index) + " Record have been removed from Database Successfully", "Info", 1);
            }else{
               JOptionPane.showMessageDialog(rootPane, "Error removing to Database", "Error", 0); 
            }
            
            
        }catch(RuntimeException ex){
            
            if (txtCustomerID.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane,"CustomerID is Empty","Error",0);
            }
            if(Value.equals("Watch Sale")){
                if(txtWiD.getText().isEmpty()) {
                JOptionPane.showMessageDialog(rootPane,"Watch ID is Empty","Error",0);
                }
            }else if (Value.equals("Watch Repair")){
                if(txtWiD.getText().isEmpty()) {
                JOptionPane.showMessageDialog(rootPane,"Watch Repair ID is Empty","Error",0);
                }
            }
            if(txtInvoiceID.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane,"InvoiceID is Empty","Error",0);
            }
            if (txtPrice.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane,"Price is Empty","Error",0);
            }
            if (txtQuantity.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane,"Quantity is Empty","Error",0);
            } 
            if (txtDate.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane,"Date is Empty","Error",0);
            }
        }
    }//GEN-LAST:event_btnRemoveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageInvoicesView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageInvoicesView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageInvoicesView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageInvoicesView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageInvoicesView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelwID;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRemove;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> jcbSalesType;
    private javax.swing.JLabel lblQty;
    private javax.swing.JTextField txtCustomerID;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtInvoiceID;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTextField txtWiD;
    // End of variables declaration//GEN-END:variables
}
